// <auto-generated />
using System;
using KYC_Cache_Service.Caching;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KYC_Cache_Service.Migrations
{
    [DbContext(typeof(KYCCachingContext))]
    [Migration("20251028203135_DbModels")]
    partial class DbModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KYC_Cache_Service.Models.AddressDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.EmailDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.KYCItemDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KYCFormId")
                        .HasColumnType("int");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KYCItem");
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.PersonalDetailsDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalDetails");
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.PhoneNumberDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.AddressDbModel", b =>
                {
                    b.OwnsOne("KYCCore.Models.Address", "Data", b1 =>
                        {
                            b1.Property<int>("AddressDbModelId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AddressDbModelId");

                            b1.ToTable("Address");

                            b1.WithOwner()
                                .HasForeignKey("AddressDbModelId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.EmailDbModel", b =>
                {
                    b.OwnsOne("KYCCore.Models.Email", "Data", b1 =>
                        {
                            b1.Property<int>("EmailDbModelId")
                                .HasColumnType("int");

                            b1.Property<string>("EmailAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Preferred")
                                .HasColumnType("bit");

                            b1.HasKey("EmailDbModelId");

                            b1.ToTable("Email");

                            b1.WithOwner()
                                .HasForeignKey("EmailDbModelId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.KYCItemDbModel", b =>
                {
                    b.OwnsOne("KYCCore.Models.KYCItem", "Data", b1 =>
                        {
                            b1.Property<int>("KYCItemDbModelId")
                                .HasColumnType("int");

                            b1.Property<string>("Key")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("KYCItemDbModelId");

                            b1.ToTable("KYCItem");

                            b1.WithOwner()
                                .HasForeignKey("KYCItemDbModelId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.PersonalDetailsDbModel", b =>
                {
                    b.OwnsOne("KYCCore.Models.PersonalDetails", "Data", b1 =>
                        {
                            b1.Property<int>("PersonalDetailsDbModelId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SurName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PersonalDetailsDbModelId");

                            b1.ToTable("PersonalDetails");

                            b1.WithOwner()
                                .HasForeignKey("PersonalDetailsDbModelId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("KYC_Cache_Service.Models.PhoneNumberDbModel", b =>
                {
                    b.OwnsOne("KYCCore.Models.PhoneNumber", "Data", b1 =>
                        {
                            b1.Property<int>("PhoneNumberDbModelId")
                                .HasColumnType("int");

                            b1.Property<string>("Number")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Preferred")
                                .HasColumnType("bit");

                            b1.HasKey("PhoneNumberDbModelId");

                            b1.ToTable("PhoneNumber");

                            b1.WithOwner()
                                .HasForeignKey("PhoneNumberDbModelId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
